name: 'hardenedBSD CI'
description: 'Run CI commands in a hardenedBSD virtual machine'
inputs:
  release:
    description: 'The hardenedBSD release'
    required: false
    default: '15-STABLE'
  arch:
    description: 'CPU architecture'
    required: false
    default: 'amd64'
  filesystem:
    description: 'Filesystem'
    required: false
    default: 'ufs'
  run:
    description: 'The command to run in the hardenedBSD VM'
    required: false
    default: 'uname -a'

branding:
  icon: 'activity'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Build VM
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go run ./...

      env:
        INPUT_RUN: ${{ inputs.run }}
        INPUT_RELEASE: ${{ inputs.release }}
        INPUT_ARCH: ${{ inputs.arch }}
        INPUT_FILESYSTEM: ${{ inputs.filesystem }}