name: 'HardenedBSD CI'
description: 'Run CI commands in a HardenedBSD virtual machine'
inputs:
  release:
    description: 'The HardenedBSD release'
    required: false
    default: '15-STABLE'
  arch:
    description: 'CPU architecture'
    required: false
    default: 'amd64'
  filesystem:
    description: 'Filesystem'
    required: false
    default: 'zfs'
  run:
    description: 'The command to run in the HardenedBSD VM'
    required: false
    default: 'uname -a'
  memory:
    description: 'VM memory size (default: 4G)'
    required: false
    default: '4G'

branding:
  icon: 'activity'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Set permissions
      shell: bash
      run: |
        sudo chmod o+x /home/runner
        sudo chmod o+x /home/runner/work
        sudo chmod -R o+x /home/runner/work/hardenedbsd-vm

    - name: Build VM
      shell: bash
      run: |
        cd ${{ github.action_path }}
        sudo -E go run ./...

      env:
        INPUT_RUN: ${{ inputs.run }}
        INPUT_MEMORY: ${{ inputs.memory }}
        INPUT_CACHE: ${{ inputs.cache }}