name: 'HardenedBSD CI'
description: 'Run CI commands in a HardenedBSD virtual machine'
inputs:
  release:
    description: 'The HardenedBSD release (default: 15.0-RELEASE)'
    required: false
    default: '15.0-RELEASE'
  arch:
    description: 'CPU architecture (default: amd64)'
    required: false
    default: 'amd64'
  filesystem:
    description: 'Filesystem type (default: zfs)'
    required: false
    default: 'zfs'
  run:
    description: 'The command to run in the HardenedBSD VM'
    required: false
    default: 'uname -a'
  memory:
    description: 'VM memory size (default: 4G)'
    required: false
    default: '4G'

branding:
  icon: 'activity'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Build
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go build -o setup-action ./cmd/setup-action

    - name: Setup
      shell: bash
      run: |
        cd ${{ github.action_path }}
        ./setup-action

      env:
        INPUT_RUN: ${{ inputs.run }}
        INPUT_MEMORY: ${{ inputs.memory }}
        INPUT_CACHE: ${{ inputs.cache }}